### ISSUE TITLE
Optionally turn off multilanguage support

### ISSUE THREAD

**Issue by krlklm** [texnixe/kirby-clonr#2]
I'm using the plugin to copy pages. My site has multilanguage support, but for these pages i just want to use the default language (.de). In my blueprint every field has the option`translate: false`. When i save a new page it works as expected and just writes one file (blueprint_name.de). But when i copy the page with clonr it saves two versions (blueprint_name.de and blueprint_name.en). Is there an option to turn this off? Thanks!

**Comment by texnixe** [comment]
There is no such option but it should be easy to implement. For the time being, you could comment out lines 92 to 94 of this file:

https://github.com/texnixe/kirby-clonr/blob/4a5b20480fda378248b996d819c24d014e7959f6/field/clonr.php#L92

**Comment by krlklm** [comment]
That will work for me. Thanks for the quick reply.
